[tox]
envlist = py3

[testenv]
commands = python -m pytest -vv --junit-xml=junit_report.xml --cov-report=term --cov-report=xml:cov_report.xml --cov=casbin_couchbase_adapter tests/
deps =
    pytest
    pytest-cov
    pytest-mock
    -rrequirements.txt
    -rdev_requirements.txt
